/*
 * Vercel serverless function: POST /api/export-pdf
 *
 * Body: { lesson } — the canonical lesson object described at the top of
 * render-slides-html.js (already generated by /api/generate-lesson, no new
 * AI call happens here).
 *
 * Renders all 18 slides (real Canva template backgrounds + the lesson's
 * text laid out at the template's exact original coordinates) to HTML,
 * then prints that HTML to a PDF with headless Chromium
 * (puppeteer-core + @sparticuz/chromium, the standard combo for running a
 * real browser inside a Vercel serverless function) and streams the PDF
 * back as a download.
 */

const chromium = require("@sparticuz/chromium");
const puppeteer = require("puppeteer-core");
const { buildSlidesHtml } = require("../render-slides-html");
const { CANVAS_W, CANVAS_H } = require("../slide-layouts");

module.exports = async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" });
    return;
  }

  const { lesson } = req.body || {};
  if (!lesson) {
    res.status(400).json({ error: "Falta 'lesson' no corpo da requisição." });
    return;
  }

  let browser;
  try {
    const html = buildSlidesHtml(lesson);

    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: { width: CANVAS_W, height: CANVAS_H },
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    // Give @font-face (Google Fonts) time to finish loading before printing.
    await page.evaluateHandle("document.fonts.ready");

    const pdf = await page.pdf({
      width: `${CANVAS_W}px`,
      height: `${CANVAS_H}px`,
      printBackground: true,
      pageRanges: "",
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    });

    const safeName = (lesson.coverTitle || "conversation-maker")
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${safeName || "roteiro"}.pdf"`);
    res.status(200).send(pdf);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Falha ao gerar o PDF.", detail: String(err && err.message) });
  } finally {
    if (browser) await browser.close();
  }
};
